### ISSUE TITLE
Parent Maya GUIs to Maya main window

### ISSUE THREAD

**Issue by charliewales** [Toolchefs/kiko#1]
First, thanks for sharing this. Second, it would be very nice to parent the Maya Export and Import GUIs to the main Maya window. Otherwise each time the tools lose focus they get buried behind Maya window which is a bit annoying and unproductive. Thanks again.

**Comment by hoorayfor3d** [comment]
@charliewales I just submitted a pull request that fixes this. Tested in Maya 2017.

**Comment by danielefederico** [comment]
Thanks Michael, I just pushed it on master.
